golfproj2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('', include('roundapp.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('membersapp.urls')),
    path('', include('resumeapp.urls')),
]

mainapp/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('', views.home, name="home"),
    path('draft_home/', views.home2, name="home2"),
]

roundapp/urls.py
from django.urls import path
from .import views

# urlpatterns = [
#     path('round/', views.round_home, name="round-home"),
#     path('new_round/', views.new_round, name="new-round"),
#     path('ajax/load_tees/', views.load_tees, name="ajax-load-tees"),
#     path('round_stats/', views.round_stats, name="round-stats"),
#     #path('round_stats/<int:round_id>/', views.round_stats, name="round-stats"),
#     path('round/<int:round_id>/stats/<int:hole_number>/', views.round_stats, name='round-stats-holes'),
#     path('round/<int:round_id>/summary/', views.round_summary, name='round-summary'),
# ]

urlpatterns = [
    path('golf_home/', views.golf_home, name="golf-home"),
    # path('round/', views.round_home, name="round-home"),
    path('new_round/', views.new_round, name='new-round'),
    path('ajax/load_tees/', views.load_tees, name="ajax-load-tees"),
    path('round/<int:round_number_id>/stats/<int:hole_number>/', views.round_stats, name='round-stats'),
    #path('round_stats/', views.round_stats, name='round-stats'),
    path('round_summary/<int:round_number_id>/summary/', views.round_summary, name='round-summary'),
    path('review_data/', views.review_data, name='review-data'),
    path('save-round/', views.save_round, name='save-round'),

    path('stats_test/<int:round_number_id>/<int:hole_number>/', views.stats_test, name='stats-test'),
    path('round_csv/<int:round_number_id>', views.round_csv, name="round-csv"),

    path('check_incomplete_rounds/', views.check_incomplete_rounds, name="check-incomplete-rounds"),
    path('continue_round/<int:round_number_id>', views.continue_round, name="continue-round"),
]

roundapp/models.py
from django.db import models
from django.contrib.auth.models import User
from mainapp.models import Course, Tee, Hole, Player

class Round(models.Model):
	ROUND_TYPE_CHOICES = [
			('regular', 'Regular'),
			('practice', 'Practice'),
			('tournament', 'Tournament'),
		]

	WEATHER_CHOICES = [
			('sunny', 'Sunny'),
			('overcast', 'Overcast'),
			('rain', 'Rain'),
		]

	WIND_CHOICES = [
			('nowind', 'No Wind'),
			('lightwind', 'Light Wind'),
			('strongwind', 'Strong Wind'),
		]

	player = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
	course = models.ForeignKey(Course, on_delete=models.PROTECT, blank=True, null=True)
	tee_name = models.ForeignKey(Tee, on_delete=models.PROTECT, blank=True, null=True)
	date_played = models.DateField(blank=True, null=True)
	round_type = models.CharField(max_length=30, choices=ROUND_TYPE_CHOICES, blank=True, null=True)
	weather = models.CharField(max_length=50, choices=WEATHER_CHOICES, blank=True, null=True)
	wind = models.CharField(max_length=50, choices=WIND_CHOICES, blank=True, null=True)
	comments = models.CharField(max_length=300, blank=True, null=True)
	is_complete = models.BooleanField(default=False)

	def __str__(self):
		return f'Round on {self.date_played} {self.course.name if self.course else "Unknown Course"}'

class RoundStats(models.Model):
	FAIRWAY_CHOICES = [
			('wayleft', 'Way Left'),
			('left', 'Left'),
			('hit', 'Hit'),
			('right', 'Way Left'),
			('wayright', 'Way Right'),
			('na', 'na')
		]

	GREEN_CHOICES = [
			('longleft', 'Long Left'),
			('long', 'Long'),
			('longright', 'Long Right'),
			('left', 'Left'),
			('hit', 'Hit'),
			('right', 'Right'),
			('shortleft', 'Short Left'),
			('short', 'Short'),
			('shortright', 'Short Right'),
			('notreach', 'Could Not Reach'),
			('na', 'na')
		]

	UPDOWN_CHOICES = [
			('yes', 'Yes'),
			('no', 'No'),
			('na', 'na')
		]

	SANDSAVE_CHOICES = [
			('yes', 'Yes'),
			('no', 'No'),
			('na', 'na')
		]

	round_number = models.ForeignKey(Round, on_delete=models.CASCADE, related_name='round_stats')
	hole_number = models.ForeignKey(Hole, on_delete=models.PROTECT, related_name='round_stats')
	par = models.IntegerField()
	score = models.IntegerField()
	fairway = models.CharField(max_length=50, choices=FAIRWAY_CHOICES, blank=True, null=True)
	drivedistance = models.IntegerField(blank=True, null=True)
	green = models.CharField(max_length=50, choices=GREEN_CHOICES, blank=True, null=True)
	putts = models.IntegerField(blank=True, null=True)
	firstputtdistance = models.IntegerField(blank=True, null=True)
	updown = models.CharField(max_length=50, choices=UPDOWN_CHOICES, blank=True, null=True)
	sandsave = models.CharField(max_length=50, choices=SANDSAVE_CHOICES, blank=True, null=True)
	penalties = models.IntegerField(blank=True, null=True)

	def __str__(self):
		return f'Stats for Hole {self.hole_number.hole_number} - Par {self.par}'

roundapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.template import loader
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import RoundForm, RoundStatsForm
from mainapp.models import Course, Tee, Hole, Player
from .models import Round, RoundStats
from .forms import StatsTestForm

from django.core.serializers.json import DjangoJSONEncoder
import json
import pandas as pd
import csv


# Test to check for incomplete rounds.
def check_incomplete_rounds(request):	
	if request.user.is_authenticated:
		incomplete_round = Round.objects.filter(player_id=request.user.id, is_complete=False).first()
		# messages.success(request, ("You have an incomplete round..."))
		if incomplete_round:
			# messages.success(request, ("To continue updating round or delete..."))
			return redirect('continue-round', round_number_id=incomplete_round.id)
			# return redirect('continue-round', round_id=incomplete_round.id)
		return redirect('golf-home')
	return None


def continue_round(request, round_number_id):
	round_instance = get_object_or_404(Round, id=round_number_id)
	if request.method =="POST":
		if 'continue'in request.POST:
			return redirect('stats-test', round_number_id=round_number_id, hole_number=1)
		elif 'delete' in request.POST:
			round_instance.delete()
			return redirect('golf-home')

	return render(request, 'roundapp/continue_round.html', {'round_instance': round_instance})

	# if request.method == 'POST':
	# 	if 'continue' in request.POST:
	# 		return redirect('enter_hole_stats', round_id=round.id)
	# 	elif 'delete' in request.POST:
	# 		round.delete()
	# 		return redirect('start_new_round')
	# return render(request, 'continue_round.html', {'round': round})





# Testing how to allow user values to show in summary page.

ROUND_TYPE_CHOICES = {
	'regular': 'Regular',
	'practice': 'Practice',
	'tournament': 'Tournament'
}

WEATHER_CHOICES = {
	'sunny': 'Sunny',
	'overcast': 'Overcast',
	'rain': 'Rain'
}

WIND_CHOICES = {
	'nowind': 'No Wind',
	'lightwind': 'Light Wind',
	'strongwind': 'Strong Wind'
}

GREEN_CHOICES = {
    'longleft': 'Long Left',
    'long': 'Long',
    'longright': 'Long Right',
    'left': 'Left',
    'hit': 'Hit',
    'right': 'Right',
    'shortleft': 'Short Left',
    'short': 'Short',
    'shortright': 'Short Right',
    'notreach': 'Could Not Reach',
    'na': 'na'
}

FAIRWAY_CHOICES = {
    'wayleft': 'Way Left',
    'left': 'Left',
    'hit': 'Hit',
    'right': 'Right',
    'wayright': 'Way Right',
    'na': 'na'
}

UPDOWN_CHOICES = {
    'yes': 'Yes',
    'no': 'No',
    'na': 'na'
}

SANDSAVE_CHOICES = {
    'yes': 'Yes',
    'no': 'No',
    'na': 'na'
}


def stats_test(request, round_number_id=None, hole_number=1):
	submitted = False
	round_instance = get_object_or_404(Round, id=round_number_id)
	hole_instance = get_object_or_404(Hole, course=round_instance.course, hole_number=hole_number)
	#messages.success(request, f'Request Method: {request.method}')

	if request.method == "POST":
		form = StatsTestForm(request.POST)
		if form.is_valid():
			#Check if round/hole entry already exists.
			try:
				updated_stats = RoundStats.objects.get(round_number=round_instance, hole_number=hole_instance)
				form = StatsTestForm(request.POST, instance=updated_stats)
				form.save()
				#messages.success(request, 'Existing data updated!')

			except RoundStats.DoesNotExist:
				stats = form.save(commit=False)
				# save the round id, hole number, and par as they are set already.
				stats.round_number = round_instance
				stats.hole_number = hole_instance
				stats.par = hole_instance.par
				stats.save()
				# messages.success(request, 'New data created!')

			if 'next' in request.POST:
				hole_number += 1
				par=hole_instance.par # This is for testing the par value only.
				#messages.success(request, f'Next worked!! Moving to hole {hole_number} with par {par}!')
				if hole_number > 18: #18: # Changed to 3 for testing purposes.
					#messages.success(request, f'Finishing round worked!! Moving to summary page!')

					# Retrieve the relevant model instances
					round_instance = get_object_or_404(Round, id=round_number_id)
					# messages.success(request, f'Round_number_id = {round_number_id}; Round_instance = {round_instance}')
					rnd = Round.objects.get(id=round_number_id)
					rnd.is_complete = True
					rnd.save(update_fields=['is_complete'])
					# messages.success(request, f'Round is_complete = {rnd.is_complete}')

					stats = RoundStats.objects.filter(round_number=round_instance)
					# messages.success(request, f'Update round #{round_number_id}')

					# Loop through the instances and update the fields based on your conditions
					for stat in stats:
						if stat.drivedistance == None:
							stat.drivedistance = -1
						if stat.firstputtdistance == None:
							stat.firstputtdistance = -1
						# Save the updated instance
						stat.save()

					return redirect('round-summary', round_number_id=round_number_id)
				return redirect('stats-test', round_number_id=round_number_id, hole_number=hole_number)
			if 'back' in request.POST:
				hole_number -= 1
				if hole_number < 1:
 					hole_number = 1
				#messages.success(request, f'Back worked!! Moving to hole {hole_number}!')
				return redirect('stats-test', round_number_id=round_number_id, hole_number=hole_number)
	else:
		#Retrieve existing data for the current hole
		try:
			previous_stats = RoundStats.objects.get(round_number=round_instance, hole_number=hole_instance)
			form = StatsTestForm(instance=previous_stats)
			#messages.success(request, 'Previous data retrieved.')
		
		except RoundStats.DoesNotExist:
			form = StatsTestForm(initial={'score': hole_instance.par})
			#messages.success(request, f'Blank form loaded - request type {request.method}!')

		# if 'submitted' in request.GET:
		# 	submitted = True

	context = {
		'form': form,
		'submitted': submitted,
		'round_number': round_instance,
		'hole': hole_instance,
		'hole_number': hole_number,
		#'next_hole_number': hole_number + 1 if hole_number < 18 else None,
		# 'previous_hole_number': hole_number - 1 if hole_number > 1 else None,
	}
	return render(request, 'roundapp/stats_test.html', context)


# def round_stats(request, round_number_id=None, hole_number=1):
# 	round_instance = get_object_or_404(Round, id=round_number_id)
# 	hole_instance = get_object_or_404(Hole, course=round_instance.course, hole_number=hole_number)
# 	messages.success(request, f"Hole stats form submitted. Request method {request.method}")
	
# 	if request.method == "POST":
# 		form = RoundStatsForm(request.POST)
# 		if form.is_valid():
# 			messages.success(request, 'Form submitted successfully!')
# 			#Check if round/hole entry already exists.
# 			try:
# 				round_stats = RoundStats.objects.get(round_number=round_instance, hole_number=hole_instance)
# 				form = RoundStatsForm(request.POST, instance=round_stats)
# 				form.save()
# 			except RoundStats.DoesNotExist:
# 				round_stats = form.save(commit=False)
# 				round_stats.round_number = round_instance
# 				round_stats.hole_number = hole_instance
# 				round_stats.par = hole_instance.par

# 				round_stats.save()
# 				print(round_stats)
# 				print(form)

#             # Determine the next or previous hole number based on the button clicked
# 			if 'next' in request.POST:
# 				next_hole_number = hole_number + 1
# 				#console.log(f"New hole is:" + hole_number)
# 				messages.success(request, 'Moving to next hole!')
# 				if next_hole_number > 18:
# 					return redirect('round-summary', round_number_id=round_number_id)
# 				return redirect('round-stats', round_number_id=round_number_id, hole_number=next_hole_number)
# 			elif 'back' in request.POST:
# 				previous_hole_number = hole_number - 1
# 				messages.success(request, 'Moving to previous hole!')
# 				if previous_hole_number < 1:
# 					previous_hole_number = 1
# 				return redirect('round-stats', round_number_id=round_number_id, hole_number=previous_hole_number)
# 	else:
#         # Retrieve existing data for the current hole
# 		try:
# 			round_stats = RoundStats.objects.get(round_number=round_instance, hole_number=hole_instance)
# 			form = RoundStatsForm(instance=round_stats)
# 			messages.success(request, 'Existing data retrieved.')
# 		except RoundStats.DoesNotExist:
# 			form = RoundStatsForm()
# 			messages.success(request, 'Blank form loaded!')

# 	context = {
# 		'form': form,
# 		'round_number': round_instance,
# 		'hole': hole_instance,
# 		'hole_number': hole_number,
# 		'next_hole_number': hole_number + 1 if hole_number < 18 else None,
# 		'previous_hole_number': hole_number - 1 if hole_number > 1 else None,

# 	}
# 	return render(request, 'roundapp/round_stats.html', context)



def golf_home(request):
	return render(request, 'roundapp/golf_home.html', {})

def load_tees(request):
	course_id = request.GET.get('course_id')
	tees = Tee.objects.filter(course_id=course_id).order_by('tee_name')
	return JsonResponse(list(tees.values('id', 'tee_name')), safe=False)

def new_round(request):
	submitted = False
	if request.method == "POST":
		form = RoundForm(request.POST, user=request.user)
		if form.is_valid():
			# This is where i need to delay the commit and add: round.player = request.user after changing model to point to User instead of Player.
			new_round = form.save(commit=False)
			# # save the round id, hole number, and par as they are set already.
			# new_round.player = request.user
			new_round.save()
			# new_round = form.save()
			#form.save()
			#messages.success(request, 'New round data created!')

			# cleaned_data = form.cleaned_data
			# cleaned_data['player'] = cleaned_data['player'].full_name
			# cleaned_data['date_played'] = cleaned_data['date_played'].strftime('%Y-%m-%d')
			# cleaned_data['course'] = cleaned_data['course'].id

roundapp/templates/roundapp/continue_round.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content%}


<br><h2>Incomplete Round</h2>
<p>You have an incomplete round from {{ round_instance.date_played }} at {{ round_instance.course }}.</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" name="continue">Continue Round</button>
    <button type="submit" name="delete">Delete Round</button>
</form>

{% endblock %}

roundapp/templates/roundapp/golf_home.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content%}

<title>Golf App Home</title>

<style>

.container-golfhome {
	max-width: 1000px;
	margin: 0 auto;
	padding: 2rem;
	box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
	border-radius: 0.5rem;
  	background-color: #fff;
}

/* Custom CSS for the jumbotron box */
.jumbotron-box {
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
  padding: 2rem;
  border-radius: 0.5rem;
  background-color: #fff;
}

/* Custom CSS for the heading */
.jumbotron-box h1 {
  font-weight: bold;
  font-size: 2.5rem;
}

.mb-2 {
    margin-bottom: 10px; /* Adjust the spacing between buttons */
}

body {
    background-image: url("{% static 'roundapp/images/RandomCourse.jpg' %}");
    background-size: cover; /* Adjust to fit the image appropriately */
    background-repeat: no-repeat;
    background-attachment: fixed; /* Optional: keeps the image fixed during scroll */
    background-position: center;
}

</style>


<br>
<!-- <h1>Golf App Home Page</h1>
<h3>This can be the landing page for the golf app...</h3>
To look at putting login / register here, or if logged in then option to begin round.
<br>
<h4>ANOTHER TEST AT MAKING CHANGES VIA GITHUB!!</h4>

<br><br>
<a href="{% url 'new-round' %}" class="btn btn-primary">Enter New Round</a>

<br>

<ul>
	{% if user.is_authenticated %}

	  <li class="nav-item">
	    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
	  </li>  
	{% else %}
	  <li class="nav-item">
	    <a class="nav-link" href="{% url 'register-user' %}">Register</a>
	  </li>

	  <li class="nav-item">
	    <a class="nav-link" href="{% url 'login' %}">Login</a>
	  </li>
	{% endif %}

</ul> -->

<div class="container-golfhome">
	<div class="jumbotron-box text-center">
	  <h1 class="display-4">Welcome to My Golf Stats App</h1>
	  <p class="lead">Track and analyse your golf rounds with ease.</p>
	  <hr class="my-4">

	{% if user.is_authenticated %}
	<!-- Logged In User: {{ user.first_name }} {{ user.last_name }}<br> -->

		<h3>Hello {{ user.first_name }}, Time to Get Started!!</h3><br>
		<div class="d-flex justify-content-center">
			<a class="btn btn-primary btn-lg" href="{% url 'new-round' %}" role="button">Enter New Round</a>
		</div>
		<div class="d-flex justify-content-end mt-2">
			<a class="btn btn-secondary btn-lg float-right" href="{% url 'logout' %}" role="button">Log Out</a>
		</div>

	{% else %}

	  <p>Sign up to get started or log in to continue.</p>
	  	<div class="d-flex justify-content-center">
	  		<div>
	  		<a class="btn btn-primary btn-lg mb-2" href="{% url 'login' %}" role="button">Log In</a><br>
	  		<a class="btn btn-secondary btn-lg mb-2" href="{% url 'guest-login' %}" role="button">Log In as Guest</a>
			</div>
		</div>
		<div class="d-flex justify-content-end mt-2">
	  		<a class="btn btn-primary btn-lg" href="{% url 'register-user' %}" role="button">Register</a>
	  	</div>		
	
	{% endif %}

	</div>
</div>


{% endblock%}

roundapp/templates/roundapp/review_data.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content%}

{% if user.is_authenticated %}

<!DOCTYPE html>
<html>
<head>
    <title>Review Data</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1>Review Data (this was a test for temp data so likely will be deleted)</h1>
        {% if data_dict %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Player</th>
                        <th>Course</th>
                        <th>Tee Name</th>
                        <th>Date Played</th>
                        <th>Type</th>
                        <th>Weather</th>
                        <th>Wind</th>
                        <th>Comments</th>
                        <!-- Add other headers as needed -->
                    </tr>
                </thead>
                <tbody>
                    {% for row in data_dict %}
                        <tr>
                            <td>{{ row.player }}</td>
                            <td>{{ row.course }}</td>
                            <td>{{ row.tee_name }}</td>
                            <td>{{ row.date_played }}</td>
                            <td>{{ row.round_type }}</td>
                            <td>{{ row.weather }}</td>
                            <td>{{ row.wind }}</td>
                            <td>{{ row.comments }}</td>
                            <!-- Add other data fields as needed round_type, weather, wind, comments-->
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

{{ data_dict }}

            <form method="post" action="{% url 'save-round' %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">Save Data</button>
            </form>
        {% else %}
            <p>No data available.</p>
        {% endif %}
    </div>
</body>
</html>

{% else %}

<div class="card" style="width: 35rem;">
  <div class="card-body">
    <h5 class="card-title">Sorry! You Must Be Logged In To View This Page...</h5>
    <h6 class="card-subtitle mb-2 text-body-secondary"></h6>
    <p class="card-text"></p>
    <a href="{% url 'login' %}" class="btn btn-outline-primary">Login Here</a>
    <a href="{% url 'home' %}" class="btn btn-outline-primary">Return to Home Page</a>
  </div>
</div>

{% endif %}

{% endblock %}

roundapp/templates/roundapp/round_stats.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content%}

{% if user.is_authenticated %}

<!-- 	<h1>Round stats page - to add form for each hole and next / back navigation here.</h1>
	<br> -->

	<h1>Round Details - This was the first version - Either replace with new version or update this one!</h1>
	<p>Round ID: {{ round_number.id }}</p>
	<p>Date Played: {{ round_number.date_played }}</p>
	<p>Course: {{ round_number.course.name }}</p>
	<p>Weather: {{ round_number.weather }}</p>
	<!-- Add more fields as needed -->

	{{round_number.}}



<style>

</style>


<h1>Round Stats for Hole {{ hole.hole_number }}: Par {{ hole.par }}</h1>


<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
 <!-- Render other form fields except score -->
<!--     {% for field in form %}
        {% if field.name != 'score' %}
            {{ field }}
        {% endif %}
    {% endfor %} -->
    <div>
        <label for="id_score">Score:</label>
        <button type="button" onclick="decrementScore()">-</button>
        <input type="text" id="id_score" name="score" value="{{ form.score.value|default:hole.par }}">
        <button type="button" onclick="incrementScore()">+</button>
    </div>

	{% if previous_hole_number %}
	    <button type="submit" class="btn btn-outline-primary" name="back">
	    <a href="{% url 'round-stats' round_number.id previous_hole_number %}">Back</a></button>
	{% endif %}
	{% if next_hole_number %}
		<button type="submit" class="btn btn-outline-primary" name="next">
	    <a href="{% url 'round-stats' round_number.id next_hole_number %}">Next</a></button>
	{% endif %}

    <button type="submit">Submit</button>

    		<button type="submit" class="btn btn-outline-primary" name="next">
	    <a href="{% url 'round-stats' round_number.id next_hole_number %}">Next</a></button>
</form>

<script>
    function incrementScore() {
        var scoreInput = document.getElementById('id_score');
        var currentValue = parseInt(scoreInput.value, 10);
        scoreInput.value = currentValue + 1;
    }

    function decrementScore() {
        var scoreInput = document.getElementById('id_score');
        var currentValue = parseInt(scoreInput.value, 10);
        if (currentValue > 1) {
            scoreInput.value = currentValue - 1;
        }
    }

    // THIS WAS THE ORIGINAL JAVASCRIPT
    // function increase() {
    //     var input = document.getElementById('id_score');
    //     input.value = parseInt(input.value) + 1;
    // }

    // function decrementScore() {
    //     var input = document.getElementById('id_score');
    //     input.value = parseInt(input.value) - 1;
    // }

</script>



<script>


document.addEventListener('DOMContentLoaded', function() {
    const radioButtons = document.querySelectorAll('.form-check-input');
    radioButtons.forEach(radio => {
        radio.addEventListener('change', function() {
            radioButtons.forEach(rb => {
                rb.nextElementSibling.classList.remove('selected');
            });
            this.nextElementSibling.classList.add('selected');
        });
    });
});


    // To handle fairway selection buttons.
    function selectOption(button, hiddenInputId, value) {
        let hiddenInput = document.getElementById(hiddenInputId);
        let btnGroup = button.closest('.btn-group');
        let buttons = btnGroup.querySelectorAll('.btn');

        if (button.classList.contains('active')) {
            // If the button is already active, deselect it
            button.classList.remove('active');
            hiddenInput.value = '';
        } else {
            // If the button is not active, select it and deselect others
            buttons.forEach(btn => {
                btn.classList.remove('active');
            });
            button.classList.add('active');
            hiddenInput.value = value;
        }
    }


        function selectgreenOption(button, hiddenInputId, value) {
        let hiddenInput = document.getElementById(hiddenInputId);
        let btnGroup = button.closest('.btn-group-vertical');
        let buttons = btnGroup.querySelectorAll('.btn');

        if (button.classList.contains('active')) {
            // If the button is already active, deselect it
            button.classList.remove('active');
            hiddenInput.value = '';
        } else {
            // If the button is not active, select it and deselect others
            buttons.forEach(btn => {
                btn.classList.remove('active');
            });
            button.classList.add('active');
            hiddenInput.value = value;
        }
    }





    function incrementScore() {
        var scoreInput = document.getElementById('id_score');
        var currentValue = parseInt(scoreInput.value, 10);
        scoreInput.value = currentValue + 1;
    }

    function decrementScore() {
        var scoreInput = document.getElementById('id_score');
        var currentValue = parseInt(scoreInput.value, 10);
        if (currentValue > 1) {
            scoreInput.value = currentValue - 1;
        }
    }

    // THIS WAS THE ORIGINAL JAVASCRIPT
    // function increase() {
    //     var input = document.getElementById('id_score');
    //     input.value = parseInt(input.value) + 1;
    // }

    // function decrementScore() {
    //     var input = document.getElementById('id_score');
    //     input.value = parseInt(input.value) - 1;
    // }

</script>

{% else %}

<div class="card" style="width: 35rem;">
  <div class="card-body">
    <h5 class="card-title">Sorry! You Must Be Logged In To View This Page...</h5>
    <h6 class="card-subtitle mb-2 text-body-secondary"></h6>
    <p class="card-text"></p>
    <a href="{% url 'login' %}" class="btn btn-outline-primary">Login Here</a>
    <a href="{% url 'home' %}" class="btn btn-outline-primary">Return to Home Page</a>
  </div>
</div>

{% endif %}

{% endblock%}